mybatis: 
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://bdm282742337.my3w.com:3306/bdm282742337_db?useUnicode=true&characterEncoding=utf-8
      type: com.alibaba.druid.pool.DruidDataSource
      username: bdm282742337
      password: gpj@4212395
  mapper-locations: classpath:mybatis/*.xml #mybatis配置文件
  type-aliases-package: com.gpj.springboot.formwork #别名