server:
  port: 9999 #端口
  servlet:
    context-path: / #工程名
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/ #eureka注册端地址
spring:
  application:
    name: gateway #eureka注册名称
zuul:
  routes:
    xy-main:
      path: /**/**
      url: http://localhost/
      custom-sensitive-headers: true
  add-host-header: true